### ISSUE TITLE
Design Pattern

### ISSUE THREAD

**Issue by rababber** [eismso/Viergewinnt#1]
Theorie Software Design: Design Pattern erarbeiten

**Comment by s05882** [comment]
Memento Pattern ausarbeiten

**Comment by eismso** [comment]
State Pattern ausarbeiten

**Comment by s05882** [comment]
Memento Design Pattern comitten durch rababber da durch neue Konfiguration der Sphinx Doku Ordnerstruktur auf meinem Gerät verändert wurde, Sphinx Doku muss manuell committet werden da keine Verbindung zum github repo mehr besteht.

**Comment by rababber** [comment]
Decorator Pattern ausarbeiten

**Comment by s05882** [comment]
Pattern formatieren

**Comment by eismso** [comment]
abgeschlossen mit commit 65afd783e906a2352da214e7bac4de5430e64340
